services:
  business-db-pg:
    image: postgres
    container_name: business-db-pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "10010:5432"
  business-db-mongo:
    image: 'mongo:latest'
    container_name: business-db-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "10020:27017"
  bi-db-pg:
    image: postgres
    container_name: bi-db-pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "10030:5432"
  data-injector:
    depends_on:
      business-db-pg:
        condition: service_started
      business-db-mongo:
        condition: service_started
    build:
      context: ./datainjector
      dockerfile: Dockerfile
    container_name: data-injector
    restart: always
    environment:
      MONGO_URL: mongodb://admin:admin123@business-db-mongo:27017
      POSTGRES_DSN: host=business-db-pg port=5432 user=admin password=admin123 dbname=postgres
  metabase:
    depends_on:
      bi-db-pg:
        condition: service_started
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "10000:3000"

    
